### ISSUE TITLE
To-Do's Section

### ISSUE THREAD

**Issue by mel-habip** [mel-habip/praeficio#6]
- [x] DB Table for `to_do_s` with "category" column
- [x] BE endpoints for `to_do_s`
    - [x]  fetch all per user_id
    - [x]  toggle `completed` for one
    - [ ]  delete one
    - [x]  archive all completed
    - [x]  edit one
- [x] FE create additional categories pathway (under Settings page)
- [x] Search bar on both current and archived pages
- [x] Due Date mechanism
- [x] Completed on mechanism (to mark completed late or on-time)
